name = "JuliaIsingAnalysis"
uuid = "e1c3372b-0a29-4df3-afda-65ef99c4a78b"
authors = ["leonsieke <leonsieke@t-online.de>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Test = "1.11.0"
